[package]
name = "ttoken-contract"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
ttoken-types = { workspace = true }

dusk-core = { workspace = true, features = ["abi-dlmalloc"] }

[lib]
crate-type = ["cdylib"]
