on: [pull_request]

name: EMT CI

# Jobs run on core
jobs:
    dusk_analysis:
        name: Dusk Analyzer
        uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main


    fmt:
        name: Rustfmt & Clippy
        runs-on: core
        steps:
            - uses: actions/checkout@v4
            - uses: dsherret/rust-toolchain-file@v1
            - run: cargo fmt --all -- --check
            - run: make setup-compiler
            - run: make clippy

    test:
        name: Run tests
        runs-on: core
        steps:
            - uses: actions/checkout@v4
            - uses: dsherret/rust-toolchain-file@v1
            - run: make test
